version: '3'

services:
  postgres:
    image: 'postgres:10'
    container_name: 'java-postgres'
    ports:
      - "5432:5432"
    environment:
      - 'POSTGRES_USER=admin'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_DB=digdes-database'
    volumes:
      - ./imports/postgres/:/docker-entrypoint-initdb.d/

  app:
    build: ../..
    container_name: 'dig-des-app'
#    ports:
#      - "8080:8080"
#    links:
#      - 'postgres:digdes-database'


#docker ps -all
#docker-compose up -d --build
#docker rmi <id>
#docker rm <id>
#docker logs dig-des-app --follow
#docker exec -it java postgres bash
#psql -U madbrains -h localhost -d javacourse
#-d